### ISSUE TITLE
npm install dependency error (esprima-six)

### ISSUE THREAD

**Issue by bhagavate** [anvaka/ngraph.three#2]
hello

npm install failed with 

npm ERR! node v4.1.1
npm ERR! npm  v2.14.4
npm ERR! code E404

npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/esprima-six
npm ERR! 404
npm ERR! 404 'esprima-six' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'derequire'

looks like there is no such module as 'esprima-six' anymore in npm repository 
https://www.npmjs.com/package/esprima-six

**Comment by anvaka** [comment]
Thanks! This module was using very old version of browserify.

I updated dependencies and published this as version 0.0.13 to npm. Should be working now.

**Comment by bhagavate** [comment]
thanks!
