### ISSUE TITLE
Library referencing its own version of threejs instead of as peer

### ISSUE THREAD

**Issue by dflor003** [anvaka/ngraph.three#4]
This library is essentially a plugin to threejs but it is referencing its own version of three.js which makes it particularly impossible to use it in a project that brings in and references three.js from npm. This also means that it would always use the version in its package.json instead of being able to upgrade to the latest via npm.

**Steps to reproduce:**
1. Create a new nodejs project and set it up to use webpack for dependency management
2. Run `npm install --save three ngraph.three`
3. Build out a simple graph
4. Override the `createNodeUI` method to something like this:
```
import * as createGraph from 'ngraph.graph';
import * as ngraphThree from 'ngraph.three';
import { MeshPhongMaterial, SphereGeometry, Mesh } from 'three;

const graph = ...; // Build out any graph
const graphics = this.graphics = ngraphThree(graph);
graphics.createNodeUI(node => createNodeGraphics(node));
graphics.run();

function createNodeGraphics(node) {
  const geometry = new SphereGeometry(10);
  const material = new MeshPhongMaterial({
    color: 0x4e85d4
  });
  return new Mesh(geometry, material);
}
```

**Expected:**
Builds out mesh based off `createNodeGraphics` method

**Actual:**
Bunch of errors in the console due to `Mesh` from the project's `node_modules/three` package not being an instance of `Object3D` from `node_modules/ngraph.three/lib/three.js'. This is since the `three.js` library is effectively being imported twice

**Comment by anvaka** [comment]
Thanks for the PR! Merged it and published as `v0.0.15`
